//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Testovyjj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Обращение.
    /// </summary>
    // *** Start programmer edit section *** (Обращение CustomAttributes)

    // *** End programmer edit section *** (Обращение CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОбращениеE", new string[] {
            "Номер as \'Номер\'",
            "Статус as \'Статус\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Имя as \'Имя\'",
            "НаОснове as \'На основе\'",
            "НаОснове.Статус as \'Статус\'"}, Hidden=new string[] {
            "Сотрудник.Имя",
            "НаОснове.Статус"})]
    [MasterViewDefineAttribute("ОбращениеE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    [MasterViewDefineAttribute("ОбращениеE", "НаОснове", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Статус")]
    [View("ОбращениеL", new string[] {
            "Номер as \'Номер\'",
            "Статус as \'Статус\'",
            "Сотрудник.Имя as \'Имя\'",
            "НаОснове.Статус as \'Статус\'"})]
    public class Обращение : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fСтатус;
        
        private IIS.Testovyjj.Обращение fНаОснове;
        
        private IIS.Testovyjj.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (Обращение CustomMembers)

        // *** End programmer edit section *** (Обращение CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Номер CustomAttributes)

        // *** End programmer edit section *** (Обращение.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Номер Get start)

                // *** End programmer edit section *** (Обращение.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Обращение.Номер Get end)

                // *** End programmer edit section *** (Обращение.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Номер Set start)

                // *** End programmer edit section *** (Обращение.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Обращение.Номер Set end)

                // *** End programmer edit section *** (Обращение.Номер Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Статус CustomAttributes)

        // *** End programmer edit section *** (Обращение.Статус CustomAttributes)
        [StrLen(255)]
        public virtual string Статус
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Статус Get start)

                // *** End programmer edit section *** (Обращение.Статус Get start)
                string result = this.fСтатус;
                // *** Start programmer edit section *** (Обращение.Статус Get end)

                // *** End programmer edit section *** (Обращение.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Статус Set start)

                // *** End programmer edit section *** (Обращение.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Обращение.Статус Set end)

                // *** End programmer edit section *** (Обращение.Статус Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.НаОснове CustomAttributes)

        // *** End programmer edit section *** (Обращение.НаОснове CustomAttributes)
        public virtual IIS.Testovyjj.Обращение НаОснове
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.НаОснове Get start)

                // *** End programmer edit section *** (Обращение.НаОснове Get start)
                IIS.Testovyjj.Обращение result = this.fНаОснове;
                // *** Start programmer edit section *** (Обращение.НаОснове Get end)

                // *** End programmer edit section *** (Обращение.НаОснове Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.НаОснове Set start)

                // *** End programmer edit section *** (Обращение.НаОснове Set start)
                this.fНаОснове = value;
                // *** Start programmer edit section *** (Обращение.НаОснове Set end)

                // *** End programmer edit section *** (Обращение.НаОснове Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Обращение.Сотрудник CustomAttributes)
        [NotNull()]
        public virtual IIS.Testovyjj.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Сотрудник Get start)

                // *** End programmer edit section *** (Обращение.Сотрудник Get start)
                IIS.Testovyjj.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Обращение.Сотрудник Get end)

                // *** End programmer edit section *** (Обращение.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Сотрудник Set start)

                // *** End programmer edit section *** (Обращение.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Обращение.Сотрудник Set end)

                // *** End programmer edit section *** (Обращение.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОбращениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбращениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбращениеE", typeof(IIS.Testovyjj.Обращение));
                }
            }
            
            /// <summary>
            /// "ОбращениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбращениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбращениеL", typeof(IIS.Testovyjj.Обращение));
                }
            }
        }
    }
}
